### ISSUE TITLE
Explain linkage between encryption info and component

### ISSUE THREAD

**Issue by hannestschofenig** [suit-wg/suit-firmware-encryption#12]
In the firmware encryption draft we have defined an extension to the envelope that indicates what encryption parameters are applied to which component. 

Here is the CDDL:

```
     suit-protection-wrappers => bstr .cbor {
         *(int/str) => [+ SUIT_Encryption_Info]
     }
```

Currently the text provides no explanation or an example of how this linkage works.

**Comment by hannestschofenig** [comment]
This aspect is related to https://github.com/suit-wg/suit-firmware-encryption/pull/8 and to the mailing list discussion https://mailarchive.ietf.org/arch/msg/suit/9ZeqNixEZ8HhTTxkXypTQmmfLOM/

**Comment by hannestschofenig** [comment]
This issue is also related to https://github.com/suit-wg/suit-firmware-encryption/issues/7

**Comment by kentakayama** [comment]
With [this sample SUIT Manifest](https://github.com/suit-wg/suit-firmware-encryption/pull/20/files#diff-d466f28b286ba458d991511a53ab4f502bd2645daa358779a6597a2714623e1fR40) in PR #20, this issue is solved.
