### ISSUE TITLE
Complete example

### ISSUE THREAD

**Issue by hannestschofenig** [suit-wg/suit-firmware-encryption#13]
The draft is missing a complete example

**Comment by kentakayama** [comment]
PR #20 adds minimum example for the case where the Author knows the Devices and uses AES-KW.

TODO
- Add an example using HPKE
- Add an example for the case where the Author doesn't know the Devices (if necessary)

**Comment by hannestschofenig** [comment]
One complete example is in the draft. As a bonus, we could add an example based on ES-DH.
